# Generated by Django 5.2.8 on 2025-12-10 19:00

from django.db import migrations

def update_images(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Product = apps.get_model('products', 'Product')
    
    blob_base_url = "https://32vzkt6aqmhvgt9v.public.blob.vercel-storage.com/seed/"
    
    # Update Categories
    categories_map = {
        'kitchenware': 'cat_kitchenware.png',
        'fashion': 'cat_fashion.png',
        'catering': 'cat_catering.png',
        'electronics': 'cat_electronics.png',
    }
    
    for slug, image_name in categories_map.items():
        Category.objects.filter(slug=slug).update(image=f"{blob_base_url}{image_name}")
        
    # Update Products
    products_map = {
        'premium-gold-chafing-dish-8l': 'cat_kitchenware.png',
        'non-stick-cookware-set': 'cat_kitchenware.png',
        'ladies-high-waist-jeans': 'cat_fashion.png',
        'summer-floral-dress': 'cat_fashion.png',
        'stainless-steel-buffet-server': 'cat_catering.png',
        'commercial-juice-dispenser': 'cat_catering.png',
        'smart-led-tv-43-inch': 'cat_electronics.png',
        'bluetooth-soundbar': 'cat_electronics.png',
    }
    
    for slug, image_name in products_map.items():
        Product.objects.filter(slug=slug).update(image_main=f"{blob_base_url}{image_name}")

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_image_alter_product_image_main'),
    ]

    operations = [
        migrations.RunPython(update_images),
    ]
