# Generated by Django 5.2.8 on 2025-12-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='List of product options (e.g. Size, Color)'),
        ),
    ]
