# Generated by Django 5.2.8 on 2025-11-29 14:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('theme_mode', models.CharField(choices=[('default', 'Default Blue/Gold'), ('dark', 'Dark Mode'), ('red', 'Red Mode (Flash Sale)'), ('green', 'Green Mode (Holiday)')], default='default', max_length=20)),
                ('primary_color', models.CharField(blank=True, help_text='Hex code e.g. #FF0000', max_length=7, null=True)),
                ('accent_color', models.CharField(blank=True, max_length=7, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('products', models.ManyToManyField(blank=True, related_name='campaigns', to='products.product')),
            ],
        ),
    ]
