# Generated by Django 5.2.8 on 2025-12-17 12:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('products', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='product_selection_type',
            field=models.CharField(choices=[('manual', 'Manual Selection'), ('category', 'Category Based'), ('all', 'All Products')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='products.category'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='theme_mode',
            field=models.CharField(choices=[('default', 'Default Blue/Gold'), ('dark', 'Dark Mode'), ('red', 'Red Mode (Flash Sale)'), ('green', 'Green Mode (Holiday)'), ('custom', 'Custom Colors')], default='default', max_length=20),
        ),
        migrations.CreateModel(
            name='CampaignBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('top_bar', 'Top Notification Bar'), ('hero_slide', 'Hero Carousel Slide'), ('flash_sale', 'Flash Sale Section'), ('popup', 'Popup Modal'), ('sidebar', 'Sidebar Ad')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('subheading', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/banners/')),
                ('link', models.CharField(blank=True, help_text='URL to redirect to', max_length=500)),
                ('button_text', models.CharField(blank=True, default='Shop Now', max_length=50)),
                ('display_pages', models.JSONField(default=list, help_text="List of pages to show this banner e.g. ['/', '/shop']")),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='campaigns.campaign')),
            ],
        ),
    ]
