# Generated by Django 5.2.8 on 2025-12-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaign_created_at_alter_campaign_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage off (0-100)', max_digits=5),
        ),
    ]
