# Generated by Django 5.2.8 on 2025-12-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignbanner',
            name='theme_mode',
            field=models.CharField(choices=[('inherit', 'Inherit from Campaign'), ('default', 'Default Blue/Gold'), ('dark', 'Dark Mode'), ('red', 'Red Mode (Flash Sale)'), ('green', 'Green Mode (Holiday)'), ('custom', 'Custom Colors')], default='inherit', max_length=20),
        ),
    ]
