# Generated by Django 5.2.8 on 2025-12-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_latitude_order_delivery_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Castle Depots', max_length=255)),
                ('store_address', models.TextField(help_text='Physical address of the store')),
                ('latitude', models.FloatField(help_text='Store latitude for distance calculation')),
                ('longitude', models.FloatField(help_text='Store longitude for distance calculation')),
                ('cost_per_km', models.DecimalField(decimal_places=2, default=50.0, help_text='Cost per kilometer in KES', max_digits=10)),
                ('base_shipping_cost', models.DecimalField(decimal_places=2, default=200.0, help_text='Minimum base shipping cost', max_digits=10)),
                ('max_delivery_distance', models.FloatField(default=50.0, help_text='Maximum delivery distance in KM')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Store Settings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
