# Generated by Django 5.2.8 on 2025-12-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_storesettings_order_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_options',
            field=models.JSONField(blank=True, default=dict, help_text='Selected options for this item'),
        ),
    ]
