# Generated by Django 5.2.8 on 2025-12-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_processing', 'Order Processing'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('flash_sale', 'Flash Sale Alert'), ('new_product', 'New Product Available'), ('price_drop', 'Price Drop Alert'), ('back_in_stock', 'Back in Stock'), ('wishlist_sale', 'Wishlist Item on Sale'), ('account_update', 'Account Update'), ('security_alert', 'Security Alert'), ('review_reminder', 'Review Reminder'), ('support_response', 'Support Response'), ('promotion', 'Promotional Offer'), ('system', 'System Message')], max_length=30),
        ),
    ]
